// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cores/AmareloLimao.tsx": () => import("../components/mockups/cores/AmareloLimao.tsx"),
  "./components/mockups/cores/AmareloNeon.tsx": () => import("../components/mockups/cores/AmareloNeon.tsx"),
  "./components/mockups/cores/AmareloOuro.tsx": () => import("../components/mockups/cores/AmareloOuro.tsx"),
  "./components/mockups/cores/Ambar.tsx": () => import("../components/mockups/cores/Ambar.tsx"),
  "./components/mockups/cores/AzulEletrico.tsx": () => import("../components/mockups/cores/AzulEletrico.tsx"),
  "./components/mockups/cores/Coral.tsx": () => import("../components/mockups/cores/Coral.tsx"),
  "./components/mockups/cores/Dourado.tsx": () => import("../components/mockups/cores/Dourado.tsx"),
  "./components/mockups/cores/Indigo.tsx": () => import("../components/mockups/cores/Indigo.tsx"),
  "./components/mockups/cores/Turquesa.tsx": () => import("../components/mockups/cores/Turquesa.tsx")
};
